# Generated by Django 5.0.4 on 2024-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gestor', '0002_rename_monto_gasto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('supermercado', 'Supermercado'), ('transporte', 'Transporte'), ('casa', 'Casa'), ('ocio', 'Ocio')], default='', max_length=20),
        ),
    ]
