# Generated by Django 5.0.4 on 2024-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gestor', '0003_gasto_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GastoCasa',
        ),
    ]
