# Generated by Django 5.0.4 on 2024-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gestor', '0004_delete_gastocasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestomensual',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuestomensual',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
