# Generated by Django 5.0.4 on 2024-04-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gestor', '0006_categoria_remove_gasto_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestomensual',
            name='usuario',
        ),
    ]
